### ISSUE TITLE
False positive: ComparingUnrelatedTypes comparing long to int constant

### ISSUE THREAD

**Issue by RichardBradley** [sksamuel/scapegoat#111]
Comparing a long to an int constant works fine in Scala:

```
scala> def isM1(x: Long) = {
     |  x == -1
     | }
isM1: (x: Long)Boolean

scala> isM1(2)
res0: Boolean = false

scala> isM1(-1L)
res1: Boolean = true
```

.. but `scapegoat` warns that this is an "equality comparison that cannot succeed".

The following failing test can be added to "ComparingUnrelatedTypesTest", but I think it should pass:

```
      "for long compared to int constant" in {
        val code = """object A { val l = 100L; val b = l == -1 } """
        compileCodeSnippet(code)
        compiler.scapegoat.feedback.warnings.size shouldBe 0
      }
```

(as a matter of style, I think "L" is preferred over "l" for long constants, see e.g. https://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s4.8.8-numeric-literals )

**Comment by RichardBradley** [comment]
I'm not that familiar with the compiler internals / how scapegoat works (yet), but perhaps the underlying bug here is that the "ComparingUnrelatedTypesTest" rule runs before the compiler promotes the int constant to a long constant?

**Comment by cldellow** [comment]
A related case is comparing a byte to a char, which commonly happens in file parsers.

eg:

```(10:Byte) == '\n'
res1: Boolean = true```

But this will trigger the ComparingUnrelatedTypes check. I suspect it's far more common that a byte to char comparison is a false positive than a legitimate bug, given the rarity of the byte type in the first place.

**Comment by diversit** [comment]
I have a similar issue comparing mutable and immutable maps.
Map("one" -> 1) == collection.mutable.Map("one" -> 1) yields 'true'. So it seems to do exactly what is expected so should it be marked as a ComparingUnrelatedType or not?

**Comment by JoshRosen** [comment]
@RichardBradley @cldellow, I've created a PR (#160) which aims to fix both of your false-positives. The idea is to leverage the fact that you're comparing to literals, in which case we can determine whether the literal's value fits within the range of the other value's type.

@diversit, I think that comparison of mutable and immutable maps is a different category of false-positive and probably should be a different bug. It looks like the current logic checks whether there's a subtype/supertype/same-type relationship between the two types, but according to http://docs.scala-lang.org/tutorials/FAQ/collections those two map classes are both children of a common supertype and thus are not considered related. My guess is that this type of comparison for Scala standard collection libraries might need to be special-cased.
