### ISSUE TITLE
False Positive: UnsafeContains

### ISSUE THREAD

**Issue by hzwaal** [sksamuel/scapegoat#124]
I'm not entirely sure that this is an issue, but AFAICS the code functions correctly. The issue is probably caused by the covariance of `Seq`. For `Set`s it reports no error.

``` Scala
  val words = Seq("Hello", "world")
  val moreWords = Seq("Goodbye", "cruel", "world")
  // UnsafeContains: below code gives a false positive
  val common = moreWords.filter(words.contains)
```

**Comment by Axblade** [comment]
I created a test to prove this false positive and received unexpected result: scapegoat did not raise the warning there.

**Comment by hzwaal** [comment]
That's strange. I just tried the 4 lines from above directly in one of my projects and it still gives an error:
```
[error] UnsafeContains.scala:7: Unsafe contains
          UnsafeContains.this.words.contains[Any](elem)

[error] src/main/scala/UnsafeContains.scala:7: Unsafe contains
[error]   val common = moreWords.filter(words.contains)
[error]                                       ^
```
project/plugins.sbt: `addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat" % "1.0.4")`
build.sbt: `scapegoatVersion := "1.2.0"`

**Comment by Axblade** [comment]
@hzwaal could you add more details about your environment? 
just wondering if it could be related to Scala versions

**Comment by hzwaal** [comment]
```
project/build.properties: sbt.version=0.13.9
project/plugins.sbt: addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat" % "1.0.4")
build.sbt: scalaVersion := "2.11.8"
build.sbt: scapegoatVersion := "1.2.0"
build.sbt: scalacOptions ++= Seq("-feature", "-unchecked", "-deprecation", "-encoding", "utf8")
```
```
$ javac -version
javac 1.8.0_91
```

**Comment by daron666** [comment]
This code produces this warning somehow
`def distinctIndices(a: Seq[Int], b: Seq[Int]): Boolean = !a.exists(b.contains)`
Scala 2.12.3

**Comment by Axblade** [comment]
It's an interesting one. 
`a.exists(b.contains)` here we get `Any` instead of real type, that's why false positive was produced.
The fix looks a bit hacky to me, if you have suggestions - I'm ready to improve it
