### ISSUE TITLE
Use of Option.get 

### ISSUE THREAD

**Issue by lab3** [sksamuel/scapegoat#133]
It is currently flagging cases where Option.isDefined has been checked before performing a get.  Is there a way to ignore this case?

**Comment by cleverdeveloper** [comment]
Why not to use `option map { value => ... }` or `option.fold(...) { value => ... }` in this case?

**Comment by sksamuel** [comment]
Yes, I agree with @cleverdeveloper, you can avoid .get completely this way, but either way, the plugin isn't smart enough to work out if you called isDefined earlier in the scope.
