### ISSUE TITLE
False Positive: LooksLikeInterpolatedString

### ISSUE THREAD

**Issue by hzwaal** [sksamuel/scapegoat#138]
The following code gives a false positive:

``` scala
val answer = 42
val message = s"$$answer = $answer"
```

The warning is:

```
[warning] Looks Like Interpolated String
          $answer = 
```

I guess the string is analyzed again after the interpolation has already taken place.

**Comment by cchantep** [comment]
Still/Same for `f"$$foo"`

**Comment by gbersac** [comment]
As a temporary (or not) solution, you could add : `@SuppressWarnings(Array("LooksLikeInterpolatedString"))` to your code.

**Comment by xplosunn** [comment]
Opened a PR: https://github.com/sksamuel/scapegoat/pull/214

**Comment by avdv** [comment]
This should be closed, right?

**Comment by som-snytt** [comment]
There are a couple of "should be closed", which maybe should be a label. I came in through the exhaustiveness check issue, just poking my head in the door.
