### ISSUE TITLE
Publish for Scala v2.12.0

### ISSUE THREAD

**Issue by marconilanna** [sksamuel/scapegoat#141]
The [Scala 2.12.0 release train](https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md) is here. Please publish for 2.12.0 and [submit a pull request](https://github.com/scala/make-release-notes/edit/2.12.x/projects-2.12.md) to let the world know what libraries are available.

**Comment by sksamuel** [comment]
I've been busy releasing https://github.com/sksamuel/elastic4s for Elasticsearch 5.0. That should be done tonight then I can move onto this.

**Comment by Axblade** [comment]
There are some test dependencies that are not released for scala 2.12 yet, like `scaldi`.
Otherwise, check my commit, it has some ground work done.

**Comment by sksamuel** [comment]
Alright I will thanks. I can probably just remove scaldi.

**Comment by marconilanna** [comment]
@sksamuel it looks like scaldi was updated to 2.12: https://github.com/scaldi/scaldi/blob/master/CHANGELOG.md#v058-2016-11-03

**Comment by sksamuel** [comment]
1.3.0 is now released which has some bug fixes and supports 2.11 and 2.12.
