### ISSUE TITLE
False positive UnnecessaryReturnUse

### ISSUE THREAD

**Issue by dskrvk** [sksamuel/scapegoat#142]
The tool reports a warning for some cases of early return:
```scala
def someFunction(): Seq[String] {
  if (somePreconditionFailed()) {
    return Seq.empty
  }
  
  ...
  constructActualReturnedResult();
}
```

In reality this doesn't happen for every instance like this, and may be correlated with the `someFunction`'s body being fairly long.

**Comment by dskrvk** [comment]
Found https://github.com/sksamuel/sbt-scapegoat/issues/4

Just to confirm, this check is for unnecessary OR un-idiomatic returns?

**Comment by sksamuel** [comment]
The use of return in general really. It should probably be named, TryNotToUseReturn or something.

**Comment by dskrvk** [comment]
Got it. Thanks for clarifying!
