### ISSUE TITLE
VarUse reported in async macro

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/scapegoat#15]
Use of var com.sksamuel.scapegoat.inspections.VarUse
var used: private[this] var state: Int = 0

**Comment by Grimalkin8675** [comment]
Hi!
I'm also getting the `myVar is never written to, so could be a val` using [monadic-html](https://github.com/OlivierBlanvillain/monadic-html) (which uses macros if I'm not mistaken).

I reproduced it and you can find the snippet [here](https://github.com/Grimalkin8675/scapegoat-false-positive).
