### ISSUE TITLE
ScalastyleReportWriter should link to absolute path of source file

### ISSUE THREAD

**Issue by ashleymercer** [sksamuel/scapegoat#151]
The ScalastyleReportWriter class is correctly [grouping errors by source file](https://github.com/sksamuel/scapegoat/blob/master/src/main/scala/com/sksamuel/scapegoat/io/ScalastyleReportWriter.scala#L16), but it looks like the path has already been [truncated in Feedback.scala](https://github.com/sksamuel/scapegoat/blob/master/src/main/scala/com/sksamuel/scapegoat/Feedback.scala#L38):

```scala
val sourceFile = normalizeSourceFile(pos.source.file.path)
```

It doesn't look like the Checkstyle XML format is documented anywhere that I can find, but some examples I found online ([see here](http://www.sw-engineering-candies.com/blog-1/howtotransformtheresultsfromfindbugscheckstyleandpmdintoasinglehtmlreportwithxslt20andjava#TOC-File-3:-checkstyle.xml-with-tree-errors-entries), for example) show full file paths for the `name` attribute.

Since we already have the raw path when constructing the Warning instance, it should be fairly easy to fix - I'd be happy to submit a pull request if you like?

**Comment by mccartney** [comment]
Closing the issue as I think it's been resolved in #153. I haven't checked myself though.
