### ISSUE TITLE
Maven build failure

### ISSUE THREAD

**Issue by cristiantoader** [sksamuel/scapegoat#161]
I am currently trying to integrate the scalac-scapegoat-plugin_2.11 version 1.3.0 in a maven build that will integrate with SonarQube via a different plugin.

I am using scapegoat as a scala-maven-plugin compiler plugin, with the `-P:scapegoat:dataDir` arg set properly.
```
<compilerPlugins>
    <compilerPlugin>
        <groupId>com.sksamuel.scapegoat</groupId>
        <artifactId>scalac-scapegoat-plugin_2.11</artifactId>
        <version>1.3.0</version>
    </compilerPlugin>
</compilerPlugins>
```

The problem is that when finding errors during the linting process, the build fails with a compilation error: "Execution default of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed."

I was wondering if it is common behavior for the maven build to fail on scapegoat errors. Can this be suppressed somehow such that the build does not fail?

**Comment by cristiantoader** [comment]
Is it possible to add a flag such as `-P:scapegoat:reportOnly:true` that would make the plugin only generate the report, without compilation errors?

**Comment by jozic** [comment]
@cristiantoader not sure you still need this, but have you tried https://github.com/sksamuel/sbt-scapegoat#inspection-warning-level-overrides?
