### ISSUE TITLE
Untrue informational message for PreferSeqEmpty & PreferSetEmpty

### ISSUE THREAD

**Issue by melezov** [sksamuel/scapegoat#177]
While the inspection does make sense (e.g. to find where to replace `Seq()` with `Nil`), the message is simply not true, as it states that using the empty factory methods will allocate new collection objects on the heap. This has changed as of Scala 2.8.0 a while ago, as is not the case:

    Welcome to Scala version 2.8.0.final (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_45).
    Type in expressions to have them evaluated.
    Type :help for more information.

    scala> Set[String]() eq Set[Int]()
    res0: Boolean = true

I'd suggest changing the message to the generic "some people like this way of doing stuff" :D

**Comment by mccartney** [comment]
I only found the issue now, but for future generations let me provide more information. As recently I have studied this inspection and amended the warning message reported by Scapegoat (https://github.com/sksamuel/scapegoat/commit/32ea1ab7328c266b8e247119057ab0a5c92880c1#diff-c6e63d97e5fc89c8f33689accb412a4d).

In fact the result from `Set.empty` is the same object (singleton) as from `Set()`:
```
object Test extends App {
  println(java.lang.System.identityHashCode(Set[String]()))
  println(java.lang.System.identityHashCode(Set.empty[String]))
}
```
[Try it online!](https://tio.run/##lcwxDsIwDEbhnVN4TJbcAbGwhw0xmMZqU6VuhH8hooqzhy4coPv7ng1cuPf1OcsAuomB5APRZHSulbYTUX1lRVE385tDYR1DbAZZQk6iyGhXtumyJnFRcI/Y8/HhvPdHbZClov0Pu//2/gM "Scala – Try It Online")
But in the code, at least in 2.12 there's a builder object created (and thrown away immediately after).

I think it's good as it is now. Closing it. Thanks for the report!
