### ISSUE TITLE
False Positive: PartialFunctionInsteadOfMatch

### ISSUE THREAD

**Issue by purawskis** [sksamuel/scapegoat#178]
When using ten or more `list map { case _ => }` in row PartialFunctionInsteadOfMatch triggers false positive.
Can be easily reproduced by copying additional `list.map {
                       case i: Int =>
                       case s: String =>
                     }` in `PartialFunctionInsteadOfMatchTest`

**Comment by sksamuel** [comment]
I've released a new version with this change.
