### ISSUE TITLE
False negative in ComparingUnrelatedTypes

### ISSUE THREAD

**Issue by rtfpessoa** [sksamuel/scapegoat#211]
When comparing two different enumerations scapegoat does not seem to complain about the comparison.

I created an example project representing the issue here: https://github.com/rtfpessoa/comparing-unrelated-types-example

@xplosunn want to take a look at this issue?

**Comment by ogirardot** [comment]
so is it closed ?

**Comment by rtfpessoa** [comment]
@ogirardot that is right.
