### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by mwz** [sksamuel/scapegoat#273]
Looks like the release changelog was completely removed from the readme with this commit 33c86dd7910fb4c743c5c7a511d699a69ead0d86 - Is there any reason for getting rid of it @sksamuel?

If maintaining release notes is too much effort, I'd suggest giving the [Release Drafter](https://probot.github.io/apps/release-drafter) bot a try.

I personally find the release notes very useful and I'm sure others will agree with me that having a changelog is a must-have these days.

I'm happy to help set this up, but someone with write permissions will need to install the Release Drafter Github app. @mccartney, do you want to give it a try?

**Comment by mccartney** [comment]
It looks like my permissions are not enough. I guess we need @sksamuel himself (not sure if anyone else's been given higher roles here).

**Comment by sksamuel** [comment]
I can make you an admin probably. Let me check tomorrow I'm about to fly
right now.

**Comment by sksamuel** [comment]
Maybe its just a limitation of github but I cannot see where I can give you
higher access than collaborator. Perhaps if we move to an organization.

**Comment by mwz** [comment]
Actually, it's now recommended to use the release drafter github action instead as the github app has been [deprecated](https://github.com/release-drafter/release-drafter/blob/master/docs/github-app.md), so we can probably set it up regardless of the permissions. 👍 

See the action details here https://github.com/marketplace/actions/release-drafter.
