### ISSUE TITLE
Could not find method scalaCompilerPlugin() error in Gradle

### ISSUE THREAD

**Issue by sergeda** [sksamuel/scapegoat#274]
When I add two lines from docs:
```
dependencies {
    compile 'com.sksamuel.scapegoat:scalac-scapegoat-plugin_2.12:1.3.3'
    scalaCompilerPlugin "com.sksamuel.scapegoat:scalac-scapegoat-plugin_2.12:1.3.3"
}
```
I've got this error:
> Could not find method scalaCompilerPlugin() for arguments [com.sksamuel.scapegoat:scalac-scapegoat-plugin_2.12:1.3.3] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

What can it be?

**Comment by eugene-sy** [comment]
Hey @sergeda 
You also need this at least:
```
configurations {
  scalaCompilerPlugin
}
```
There is a brief description here https://github.com/sksamuel/scapegoat#gradle and an example configuration: https://gist.github.com/eugene-sy/6d637290c9c178bbd8d156c69a51ff43
