### ISSUE TITLE
Build errors when enabling plugin in Gradle

### ISSUE THREAD

**Issue by sergeda** [sksamuel/scapegoat#275]
When I enable plugin I've got number of compilation errors like:

> java.lang.NoSuchMethodError: scala.collection.immutable.$colon$colon.tl$1()Lscala/collection/immutable/List;
> Cannot find an implicit instance of pureconfig.ConfigReader

and else. What can be the cause of these errors and how to fix it? 
If I disable this plugin my project builds fine

**Comment by mccartney** [comment]
Looks like some Scala version incompatibility issue to me. What version of Scala do you use and what version of the Scapegoat plugin did you take?

**Comment by sergeda** [comment]
> Looks like some Scala version incompatibility issue to me. What version of Scala do you use and what version of the Scapegoat plugin did you take?

Thanks. You were right.
