### ISSUE TITLE
Scalastyle report doesn't match with console

### ISSUE THREAD

**Issue by sergeda** [sksamuel/scapegoat#276]
I have this configuration:

```
    scalaCompileOptions.additionalParameters = [
            "-Xplugin:" + configurations.scalaCompilerPlugin.asPath,
            "-P:scapegoat:dataDir:" + "$buildDir/reports/scapegoat",
            "-P:scapegoat:disabledInspections:FinalModifierOnCaseClass",
            "-P:scapegoat:minimalWarnLevel:info",
            "-P:scapegoat:reports:scalastyle",
            "-P:scapegoat:consoleOutput:true",
            "-P:scapegoat:verbose:true",
            "-P:scapegoat:overrideLevels:UnsafeTraversableMethods=warning:TraversableHead=warning:EmptyInterpolatedString=warning:OptionGet=warning:UnusedMethodParameter=warning"
    ]
```
and generated report has 12 number of warnings but console has 20 number of warnings. What can I do to have all warnings in report? I've tried to remove
`            "-P:scapegoat:minimalWarnLevel:info"`
it doesn't helped.

Version of Scapegoat: 1.3.11

**Comment by mwz** [comment]
Have you tried to generate an xml report and compare if the numbers match up with the scalastyle report?

**Comment by sergeda** [comment]
> Have you tried to generate an xml report and compare if the numbers match up with the scalastyle report? Which are the warnings that are missing?

Just tried it and turns out the number of warnings in scalastyle report is correct. They are just grouped by file.
