### ISSUE TITLE
Add scapegoat to Scala Steward

### ISSUE THREAD

**Issue by mwz** [sksamuel/scapegoat#280]
To keep project dependencies up to date, see https://github.com/fthomas/scala-steward.

@sksamuel are you happy for me to do this?

**Comment by sksamuel** [comment]
Absolutely.
 I use it on other projects.

**Comment by mwz** [comment]
Done - https://github.com/scala-steward-org/repos/pull/228.

**Comment by mccartney** [comment]
Oh. Wow. This is the first time I see automated PRs in my life :) Cool stuff.
