### ISSUE TITLE
CollectionPromotionToAny should not warn if collection already holds Any

### ISSUE THREAD

**Issue by terusus** [sksamuel/scapegoat#315]
The `CollectionPromotionToAny` rule creates a warning when an element is appended to a Scala collection (operator `:+`). The reason is because a type mismatch between the base collection elements and the new element would effectively return a collection of base elements `Any`.

However, if the base collection is already holding elements of type `Any` then there is no point for this rule to activate.

```scala
val xs = Seq.empty[Any]
xs :+ "hello" // should be fine
```

**Comment by mccartney** [comment]
Fixed by #319, thanks for the report.
