### ISSUE TITLE
Use squash merge to keep the git history cleaner

### ISSUE THREAD

**Issue by mwz** [sksamuel/scapegoat#320]
Can I suggest that we use squash merge when merging PRs to keep the history cleaner? I was just going over the [changes](https://github.com/sksamuel/scapegoat/compare/v1.4.1...v1.4.2) between 1.4.1 and 1.4.2 and it is so much more difficult to figure out what has changed based on the individual commit messages compared to if the merged PRs were squashed into a single commit. Where commits like e.g. "fix a typo" or "make it work" make sense in the local context of the feature branch, once the feature is complete in my opinion there's no need to include those in the main history as those commits end up being interleaved with commits from other PRs which makes the history in master quite confusing and a lot of commits are out of context.

@mccartney @sksamuel do you have any thoughts on this?

**Comment by mccartney** [comment]
Yeah. Sure. I am just not used to it (at work).

I think we can configure to enable only Squash merges for PRs: (i.e. @sksamuel can)
![image](https://user-images.githubusercontent.com/762437/77250357-d0d02080-6c47-11ea-9de6-86259d3696b1.png)

**Comment by sksamuel** [comment]
Done.

![image](https://user-images.githubusercontent.com/743706/77258245-64edb800-6c47-11ea-85b8-ee15f46b457b.png)
