### ISSUE TITLE
Housekeeping: Attach release notes to v1.4.2

### ISSUE THREAD

**Issue by mwz** [sksamuel/scapegoat#324]
The latest tag doesn't have the release notes attached to it, could we please get that sorted out?

![Screenshot 2020-03-26 at 18 00 36](https://user-images.githubusercontent.com/1190768/77680375-c5546080-6f8b-11ea-9dbc-f1a0b7ea7afd.png)

**Comment by mccartney** [comment]
Wasn't it supposed to be solved by the Drafter?

**Comment by mccartney** [comment]
Added the text manually to: https://github.com/sksamuel/scapegoat/releases/tag/v1.4.2

**Comment by mwz** [comment]
Release Drafter maintains a draft of the upcoming release with all the PR merged since the last release, but once you publish a new tag, you still need to link this draft to the new tag (this isn't something that happens automatically). Drafter will start a new release draft from that point when a next PR is merged.

**Comment by mccartney** [comment]
> you still need to link this draft to the new tag (this isn't something that happens automatically)

Maybe it's too late, but I don't see any draft for 1.4.1->1.4.2 changes. I can only see a private draft (a nice one) for whatever we have added 1.4.2.

**Comment by mwz** [comment]
> Added the text manually

You can link the existing release draft instead. To do that you can click on the edit button next to the draft and then pick a tag you want to link it to. That way the draft gets turned into an actual release in Github and from that point Drafter will create a new draft for the next release.

**Comment by mccartney** [comment]
OK. Not very intuitive. Thanks for the help.

But it didn't work as expected. I was afraid it would be the case. The draft contained already newer than 1.4.2 changes. So when I did that, we landed up with 1.4.2 claiming to have the changes it didn't have.

Now how to undo it... There seems to be no delete/undo button for a release.

**Comment by mwz** [comment]
Yeah, you need to link the draft before merging anything else after you pushed a new tag.

**Comment by mccartney** [comment]
So we need to make sure @sksamuel knows that ;)

**Comment by sksamuel** [comment]
Noted :)
