### ISSUE TITLE
False Positive: Variable Shadowing reports incorrectly in for-comprehension

### ISSUE THREAD

**Issue by hzwaal** [sksamuel/scapegoat#343]
The following code:
```scala
for {
  c <- "Hello, world!"
  if c != ','
} println(c)
```
Results in the following warning (on Scala 2.13.1):
```
VariableShadowing
val c: Char = _
  c <- "Hello, world!"
  ^
```
This is clearly incorrect since there's only a single variable. The warning is only generated if the filter is present in the for-comprehension. It seems that this is caused by the code that the compiler generates under the hood. This issue might actually be the same as https://github.com/sksamuel/scapegoat/issues/342.

**Comment by mccartney** [comment]
Fixed by #357
