### ISSUE TITLE
New version for Scala 2.13.2

### ISSUE THREAD

**Issue by neko-kai** [sksamuel/scapegoat#350]
Would be nice to get this cross-published for newly released Scala `2.13.2`. Pretty please!

**Comment by mwz** [comment]
np, I'll pick this one up

**Comment by mccartney** [comment]
#351 adds the configuration for releasing for 2.13.2. No version is released for 2.13.2 yet, thus re-opening.

**Comment by avdv** [comment]
Hi @mccartney , seems semanticdb for 2.13.2 is [here](https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.2/4.3.10/)! Is there anything left to do before rolling out a new release?

**Comment by mccartney** [comment]
I've just kicked off release of 1.4.4, should be available in Maven in some time.

Also - the Github user experience here for releasing is a nightmare. I am confused every time I try to use it. Probably that's the reason there's something wrong with our past 1.4.3. No fancy changelog in https://github.com/sksamuel/scapegoat/releases
