### ISSUE TITLE
False Positive: Variable Shadowing reports incorrectly on lambda

### ISSUE THREAD

**Issue by hzwaal** [sksamuel/scapegoat#356]
The following code:

```scala
  val list = new JList[Int]
  list.setCellRenderer((_: JList[_], value: Int, _: Int, _: Boolean, _: Boolean) => render(value))

  private  def render(value: Int) = new JLabel(value.toString)
```
Results in the following warning (tried with Scala 2.13.1):

```
VariableShadowing
def render(value: Int) = ...
           ^
```

My best guess is that this is caused by the bytecode that is generated for the lambda, but I do not agree that this is shadowing. This issue is probably related to https://github.com/sksamuel/scapegoat/issues/342.

**Comment by mccartney** [comment]
I haven't tested it, but I assume it's fixed by #357
