### ISSUE TITLE
scapegoat duplicates scala/scala-abide?

### ISSUE THREAD

**Issue by RichardBradley** [sksamuel/scapegoat#38]
It looks like Scala-core have recently come up with the same idea as `scapegoat` and are busy implementing their own scalac plugin that also duplicates Findbugs: https://github.com/scala/scala-abide

It might be worth hacking on that instead, as it's likely to capture `scapegoat`'s mindshare / user base, since it is backed by the core scala team.

(No-one else seems interested in adapting Findbugs for Scala; everyone seems to want to reinvent the wheel. Maybe I'll moan about that on the Scala mailing list.)

**Comment by mccartney** [comment]
The `scala-abide` project hasn't seen a commit in 3 years now. Also I am not sure if the private communication between the involved maintainers reached any consensus, but I'd risk a guess nothing is happening in the area. 

Thus let me close the issue. If any new plans for cooperation are shared, we can obviously reconsider.
