### ISSUE TITLE
option.get should not warn if scoped under isDefined

### ISSUE THREAD

**Issue by FFdhorkin** [sksamuel/scapegoat#384]
there's one use case where `option.get` is safe and reasonable:

```Scala
def foo(bar: Option[String]) = {
    if (bar.isDefined) {
        val example = bar.get
        // do something with example
    }
    // we no longer care whether it was defined or not
}
``` 

The current implementation of this rule forces you use `.getOrElse(somethingImpossible)` in this context. That seems undesirable to me; things like `if (false)` and empty `else { }` are anti-patterns, so using getOrElse when you know the orElse is impossible should be one, too.

**Comment by mccartney** [comment]
So completeness I believe this is idiomatic Scala version of the original snippet:
```
def foo(bar: Option[String]) = {
    bar.foreach { example =>
      // do something with example
    }
    // we no longer care whether it was defined or not
}
```
Also it's chainable with `.map` instead of `.foreach`.

**Comment by mccartney** [comment]
Having said that, I believe the warning is a proper one.
