### ISSUE TITLE
Possible false positive when method ends with `_=`

### ISSUE THREAD

**Issue by randomcoder** [sksamuel/scapegoat#388]
If a pair of methods are defined using the recommended accessor/setter style then the setter is flagged as a not recommended method name.

```
private var myValue = ""

def theValue = myValue
def myValue_=(newValue: String) myValue = newValue # Identified as not recommended name as not camel case.
```

**Comment by mccartney** [comment]
I believe this is outdated. The code seems to accept trailing `_=`, see:
https://github.com/sksamuel/scapegoat/blob/5c690f685632d4b784fb0a187ef0091ec395a233/src/main/scala/com/sksamuel/scapegoat/inspections/naming/MethodNames.scala#L26
