### ISSUE TITLE
Variable shadowing false positives

### ISSUE THREAD

**Issue by FFdhorkin** [sksamuel/scapegoat#396]
gatling has a usage pattern that can produce code that looks something like this:

```Scala
        def stillPending(session: Session): Boolean = ???

        doWhileDuring(session => stillPending(session), 60 seconds) {
            exec{ session =>
                // irrelevant
                session
            }
        }.doIf(verboseLog)(exec { session =>
            // irrelevant
            session
        })
```

Session is not shadowed because this is NOT a nested scope, although it is chained code. Each of those declarations of session (of which there are 4) is in a different scope, and due to Gatling's design, there's no way to avoid this sort of thing.

This triggers a false positive in scapegoat: 

>[error] /PATH_GOES_HERE/Util.scala:135:19: [scapegoat] Variable shadowing
[error]   Variable shadowing is very useful, but can easily lead to nasty bugs in your code. Shadowed variables can be potentially confusing to other maintainers when the same name is adopted to have a new meaning in a nested scope.
[error]   val session: io.gatling.core.session.Session = _
[error]             exec{ session =>
[error]                   ^
[error] /PATH_GOES_HERE/Util.scala:139:35: [scapegoat] Variable shadowing
[error]   Variable shadowing is very useful, but can easily lead to nasty bugs in your code. Shadowed variables can be potentially confusing to other maintainers when the same name is adopted to have a new meaning in a nested scope.
[error]   val session: io.gatling.core.session.Session = _
[error]         }.doIf(verboseLog)(exec { session =>

These more minimal examples still reproduces the same issue:
```Scala
doWhileDuring(session => true, 60 seconds) {
    exec{None}
}.exec { session =>
    session
}
```
```Scala
doWhileDuring(true, 60 seconds) {
    exec{session => session}
}.exec { session =>
    session
}
```

```Scala
exec { session =>
    session
}
.exec { session =>
    session
}
```

This has led to me littering warning suppression all over my codebase. At this point, it may be more pragmatic to just disable the rule.

If this is something that'd be tricky to detect, a way of overriding it for a specific variable type would be nice (i.e. don't give warnings for io.gatling.core.session.Session shadowing, since it's likely false positive)

In case it is helpful, most of these methods that cause issues take a `Session => Validation[T]` parameter.

Versions:
- Scala: 2.12.11
- Scapegoat: 1.4.4
- scapegoat-sbt: 1.1.0

**Comment by mccartney** [comment]
@FFdhorkin  
Sorry for coming late here. Can you test your code against 1.4.6 and report back if you still encounter warnings (without suppression)?

**Comment by FFdhorkin** [comment]
looks like it is fixed now!

**Comment by mccartney** [comment]
Great. Thanks for taking the time to check and let us know.
