### ISSUE TITLE
Publish the latest version for Scala 2.12.12

### ISSUE THREAD

**Issue by mwz** [sksamuel/scapegoat#425]
Scala 2.12.12 came out on 13 Jul which is just a few days after Scapegoat 1.4.5 was published, which means there are no 2.12.12 artefacts available for the latest version - @mccartney it would be good to publish a new minor version to make it available for 2.12.12.

**Comment by mccartney** [comment]
> it would be good to publish a new minor version to make it available for 2.12.12.

@mccartney reporting for duty.

**Comment by mccartney** [comment]
1.4.6 published.
