### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by mccartney** [sksamuel/scapegoat#433]
I know this has become controversial this year, but I continue to support [Hacktoberfest](https://hacktoberfest.digitalocean.com/). For contributors to come, we need to add `hacktoberfest` to one of list of this repo's topics (an opt-in this time).

Otherwise it says:
>  Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. 

Up to you @sksamuel, but I'd suggest we add that. I can take care of (majority) of the input flow here, even we encounter spam, which I don't think would be the case.

**Comment by sksamuel** [comment]
Why is it controversial?

**Comment by mccartney** [comment]
The project has received some (partly) bad press this year. It's been said it allegedly does more harm than good, incl. encouraging spam pull requests (meaningless PRs which fix a single character or so) adding burden to the open source maintainers (I don't agree with this opinion though).

**Comment by sksamuel** [comment]
I think anything that encourages people to get involved is good. If someone
wants to waste their time making pointless PRs, then so be it, reflects
badly on them, not others.

**Comment by sksamuel** [comment]
I've added hacktoberfest and hacktoberfest2020 to the topics.
