### ISSUE TITLE
Support for Scala 2.12.13

### ISSUE THREAD

**Issue by mr-git** [sksamuel/scapegoat#469]
Just in case - please add support for Scala 2.12.13 :)
It would be nice to get new release with https://github.com/sksamuel/scapegoat/issues/455 fix included.

Thank you!

**Comment by arixmkii** [comment]
Added in this commit https://github.com/sksamuel/scapegoat/commit/3e5df90add1544d58c8a0ecf5e91224badf068c5

**Comment by sksamuel** [comment]
1.4.7 is released.
