### ISSUE TITLE
inspection to warn for matching on true and false

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/scapegoat#47]

**Comment by philliptaylorpro** [comment]
Hi, I don't think you should add this rule. If two identical pieces of code result in different bytecode then it feels like a bug or missing feature in the compiler. As you soon as you start saying "this way = bad, this way = right" then you turn the Scala community into sheep that follow rules without understanding why, or your force every new person to become a compiler expert before they can be confident in their code. Developers be shouldn't concerned with compiler rules and vice versa, you don't want to make people do things one way only for the Scala compilers to fix it and make it bad advice that's shaped your app into something less maintainable.

I feel the same way about the "final" modifier missing on case object. I've not done something wrong, or slow and you should fix the compiler.

Anyway...just some nobodies opinion.
