### ISSUE TITLE
Please compile version for Scala 2.13.5

### ISSUE THREAD

**Issue by mr-git** [sksamuel/scapegoat#484]

**Comment by mr-git** [comment]
@sksamuel, is there a way how we could help you with this recompilation release?

**Comment by mccartney** [comment]
#488 configures sbt for Scala 2.13.5. Scapegoat release to happen after that one is merged.

**Comment by mr-git** [comment]
@mccartney, thank you!

**Comment by mccartney** [comment]
1.4.8 has been released. And it should come with Scala 2.13.5 build among others.
