### ISSUE TITLE
Please compile version for Scala 2.13.6

### ISSUE THREAD

**Issue by mr-git** [sksamuel/scapegoat#520]

**Comment by ches** [comment]
Ditto for 2.12.14, not sure it's worth a separate issue or not.

**Comment by arixmkii** [comment]
@mccartney Could you kindly check if everything was fine with publishing the built artifacts? They should be uploaded to maven cental by now, but it seems they are not.

**Comment by mccartney** [comment]
You are right. Something must've gone wrong:
https://search.maven.org/search?q=g:com.sksamuel.scapegoat%20v:1.4.9

I don't see 1.4.9 there. Looking into it - I'll use #537 for keeping the record.
