### ISSUE TITLE
Add annotation to ignore code

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/scapegoat#8]
As suggested by @RichardBradley add an annotation to ignore sections of code.

**Comment by ChrisA89** [comment]
It might be worth adding a note to https://github.com/sksamuel/sbt-scapegoat#ignoring-files that you can ignore individual lines, so it's a bit more publicised.

**Comment by gzoller** [comment]
I'm not seeing where ignoring individual lines is working.  I've got this:

    @SuppressWarnings(Array("AsInstanceOf"))
    val contentAssembly = Flow[CRec].map { crec =>
      (crec, expression.render(crec.value).asInstanceOf[Message[OutputWrapper]])
    }

This compiles but still warns on .asInstanceOf.  Am I doing it wrong?

**Comment by ChrisA89** [comment]
Without trying anything, the example above doesn't have a capital A: "asInstanceOf".
Does that fix your issue?

**Comment by gzoller** [comment]
I'm afraid it didn't.  Tried cap and non-cap.  Compile worked but scapegoat still flagged the warning on .asInstanceOf
