### ISSUE TITLE
Inspection for final case classes and case objects

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/scapegoat#86]
Any benefit to a final case class? @lespea 

Akka has them:

```
final case class CloseInformation(notificationsTo: Set[ActorRef], closedEvent: Event)
final case class UpdatePendingWrite(remainingWrite: PendingWrite)
final case class WriteFileFailed(e: IOException)
```

**Comment by devkat** [comment]
Why is this issue closed? I get the error for non-final case classes, which actually conflicts with the Wartremover `FinalCaseClass` wart.

**Comment by devkat** [comment]
I see, the inspection has been removed after release 1.3.0.
