### ISSUE TITLE
maven plugin info

### ISSUE THREAD

**Issue by efisant** [sksamuel/scapegoat#87]
Can you please update "usage" section in case running the latest maven plugin?

<dependency>
    <groupId>com.sksamuel.scapegoat</groupId>
    <artifactId>scalac-scapegoat-plugin_2.11</artifactId>
    <version>0.94.5</version>
</dependency>

Thanks!

**Comment by jozic** [comment]
@sksamuel any updates on this? Do you need help with maven plugin?

**Comment by sksamuel** [comment]
Yes please, clearly when I said ASAP I really meant 3 years :)
